import Head from "next/head";
import Image from "next/image";
import { IBM_Plex_Sans } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner/banner";
import Card from "@/components/Card/Card";

const ibmPlexSans = IBM_Plex_Sans({ weight: ['400', '500', '700'], subsets: ['latin'], style: 'normal' })


export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("click!");
  };
  return (
    <>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[ibmPlexSans.className, styles.main].join(' ')}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="hero"
            width={700}
            height={400}
          />
        </div>
        <Card />
      </main>
    </>
  );
}
